/*
 * Java bean class for entity "ajustes_de_stocks" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;


/**
 * Java bean for entity "ajustes_de_stocks"
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "aaaa")
public class AjustesDeStocks extends Entity implements Serializable
{
    private static final long serialVersionUID = 1L;

    @DatabaseField(id = true)
    private Long    codigo       ; // Id or Primary Key

    @DatabaseField(canBeNull = false)
    private String     nombre       ;
    @DatabaseField(canBeNull = true)
    private Integer    existencia   ;

    /**
     * Default constructor
     */
    public AjustesDeStocks() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    
   

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : false ) 
     * @param nombre
     */
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	/**
     * Get the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Set the "existencia" field value
     * This field is mapped on the database column "existencia" ( type "INT", NotNull : false ) 
     * @param existencia
     */
    public void setExistencia( Integer existencia ) {
        this.existencia = existencia;
    }
    /**
     * Get the "existencia" field value
     * This field is mapped on the database column "existencia" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getExistencia() {
        return this.existencia;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codigo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(existencia);
        return sb.toString(); 
    } 

}
