/*
 * Created on 2019-12-28 ( Date ISO 2019-12-28 - Time 12:27:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.model;

import java.io.Serializable;
import java.math.BigDecimal;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Java bean for entity "ata" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "ata")
public class Ata extends TransportEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	@DatabaseField(canBeNull = true)
	private String nacionalidad;
	
	@DatabaseField(canBeNull = true)
	private BigDecimal acumulado ; 	

	/**
	 * Default constructor
	 */
	public Ata() {
		super();
	}
	
	public String getNacionalidad() {
		return nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}		

	public BigDecimal getAcumulado() {
		return acumulado;
	}

	public void setAcumulado(BigDecimal acumulado) {
		this.acumulado = acumulado;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(nombre);
		return sb.toString();
	}

}
