/*
 * Java bean class for entity "clientes" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "clientes"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Clientes extends Entidades implements Serializable
{
    private static final long serialVersionUID = 1L;
   

    /**
     * Default constructor
     */
    public Clientes() {
        super();
    }
}
