/*
 * Java bean class for entity "clientes" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.io.Serializable;


/**
 * Java bean for entity "clientes"
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "clientes")
public class Client extends EntityLong implements Serializable
{
    private static final long serialVersionUID = 1L;
   

    /**
     * Default constructor
     */
    public Client() {
        super();
    }
    
    @DatabaseField(canBeNull = true)
	protected String cuit; // String

	public String getCuit() {
		return cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}
    
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();       
        sb.append(nombre);
        return sb.toString(); 
    }
}
