/*
 * Java bean class for entity "comunicaciones" 
 * Created on 2019-07-06 ( Date ISO 2019-07-06 - Time 10:30:40 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "comunicaciones"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Comunicaciones implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Long    idcomunicaciones ; // Id or Primary Key

    private String     nombre       ;
    private Integer    idindicadores ;

    /**
     * Default constructor
     */
    public Comunicaciones() {
        super();
    }
    
    public Long getIdcomunicaciones() {
		return idcomunicaciones;
	}
    
	public void setIdcomunicaciones(Long idcomunicaciones) {
		this.idcomunicaciones = idcomunicaciones;
	}
	
	//----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : true ) 
     * @param nombre
     */
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Set the "idindicadores" field value
     * This field is mapped on the database column "idindicadores" ( type "INT", NotNull : false ) 
     * @param idindicadores
     */
    public void setIdindicadores( Integer idindicadores ) {
        this.idindicadores = idindicadores;
    }
    /**
     * Get the "idindicadores" field value
     * This field is mapped on the database column "idindicadores" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdindicadores() {
        return this.idindicadores;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();        
        sb.append(nombre);
        return sb.toString(); 
    } 

}
