/*
 * Java bean class for entity "indicadores" 
 * Created on 2019-07-05 ( Date ISO 2019-07-05 - Time 19:29:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "indicadores"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Indicadores implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Long    idindicadores ; // Id or Primary Key

    private String     nombre       ;
    private Integer    posicionCaracterControl ;
    private Integer    longitudCaracterControl ;
    private String     caracterControl ;
    private Integer    posicionInicioDato ;
    private Integer    longitudDato ;
    private Integer    puerto       ;
    private Integer    velocidad    ;
    private Integer    bitsDeDatos  ;
    private String     paridad      ;
    private String    bitsDeParada  ;
    private String     controlDeFlujo ;

    /**
     * Default constructor
     */
    public Indicadores() {
        super();
    }

    public Long getIdindicadores() {
		return idindicadores;
	}
	public void setIdindicadores(Long idindicadores) {
		this.idindicadores = idindicadores;
	}

	//----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : false ) 
     * @param nombre
     */
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "nombre" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Set the "posicionCaracterControl" field value
     * This field is mapped on the database column "posicion_caracter_control" ( type "INT", NotNull : false ) 
     * @param posicionCaracterControl
     */
    public void setPosicionCaracterControl( Integer posicionCaracterControl ) {
        this.posicionCaracterControl = posicionCaracterControl;
    }
    /**
     * Get the "posicionCaracterControl" field value
     * This field is mapped on the database column "posicion_caracter_control" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getPosicionCaracterControl() {
        return this.posicionCaracterControl;
    }

    /**
     * Set the "longitudCaracterControl" field value
     * This field is mapped on the database column "longitud_caracter_control" ( type "INT", NotNull : false ) 
     * @param longitudCaracterControl
     */
    public void setLongitudCaracterControl( Integer longitudCaracterControl ) {
        this.longitudCaracterControl = longitudCaracterControl;
    }
    /**
     * Get the "longitudCaracterControl" field value
     * This field is mapped on the database column "longitud_caracter_control" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getLongitudCaracterControl() {
        return this.longitudCaracterControl;
    }

    /**
     * Set the "caracterControl" field value
     * This field is mapped on the database column "caracter_control" ( type "VARCHAR", NotNull : false ) 
     * @param caracterControl
     */
    public void setCaracterControl( String caracterControl ) {
        this.caracterControl = caracterControl;
    }
    /**
     * Get the "caracterControl" field value
     * This field is mapped on the database column "caracter_control" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getCaracterControl() {
        return this.caracterControl;
    }

    /**
     * Set the "posicionInicioDato" field value
     * This field is mapped on the database column "posicion_inicio_dato" ( type "INT", NotNull : false ) 
     * @param posicionInicioDato
     */
    public void setPosicionInicioDato( Integer posicionInicioDato ) {
        this.posicionInicioDato = posicionInicioDato;
    }
    /**
     * Get the "posicionInicioDato" field value
     * This field is mapped on the database column "posicion_inicio_dato" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getPosicionInicioDato() {
        return this.posicionInicioDato;
    }

    /**
     * Set the "longitudDato" field value
     * This field is mapped on the database column "longitud_dato" ( type "INT", NotNull : false ) 
     * @param longitudDato
     */
    public void setLongitudDato( Integer longitudDato ) {
        this.longitudDato = longitudDato;
    }
    /**
     * Get the "longitudDato" field value
     * This field is mapped on the database column "longitud_dato" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getLongitudDato() {
        return this.longitudDato;
    }
    
    public String getBitsDeParada() {
		return bitsDeParada;
	}

	public void setBitsDeParada(String bitsDeParada) {
		this.bitsDeParada = bitsDeParada;
	}

	/**
     * Set the "puerto" field value
     * This field is mapped on the database column "puerto" ( type "INT", NotNull : false ) 
     * @param puerto
     */
    public void setPuerto( Integer puerto ) {
        this.puerto = puerto;
    }
    /**
     * Get the "puerto" field value
     * This field is mapped on the database column "puerto" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getPuerto() {
        return this.puerto;
    }

    /**
     * Set the "velocidad" field value
     * This field is mapped on the database column "velocidad" ( type "INT", NotNull : false ) 
     * @param velocidad
     */
    public void setVelocidad( Integer velocidad ) {
        this.velocidad = velocidad;
    }
    /**
     * Get the "velocidad" field value
     * This field is mapped on the database column "velocidad" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getVelocidad() {
        return this.velocidad;
    }

    /**
     * Set the "bitsDeDatos" field value
     * This field is mapped on the database column "bits_de_datos" ( type "INT", NotNull : false ) 
     * @param bitsDeDatos
     */
    public void setBitsDeDatos( Integer bitsDeDatos ) {
        this.bitsDeDatos = bitsDeDatos;
    }
    /**
     * Get the "bitsDeDatos" field value
     * This field is mapped on the database column "bits_de_datos" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getBitsDeDatos() {
        return this.bitsDeDatos;
    }

    /**
     * Set the "paridad" field value
     * This field is mapped on the database column "paridad" ( type "VARCHAR", NotNull : false ) 
     * @param paridad
     */
    public void setParidad( String paridad ) {
        this.paridad = paridad;
    }
    /**
     * Get the "paridad" field value
     * This field is mapped on the database column "paridad" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getParidad() {
        return this.paridad;
    }

    /**
     * Set the "controlDeFlujo" field value
     * This field is mapped on the database column "control_de_flujo" ( type "VARCHAR", NotNull : false ) 
     * @param controlDeFlujo
     */
    public void setControlDeFlujo( String controlDeFlujo ) {
        this.controlDeFlujo = controlDeFlujo;
    }
    /**
     * Get the "controlDeFlujo" field value
     * This field is mapped on the database column "control_de_flujo" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getControlDeFlujo() {
        return this.controlDeFlujo;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();        
        sb.append(nombre);       
        return sb.toString(); 
    } 

}
