/*
 * Java bean class for entity "operaciones" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "operaciones"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Operaciones extends Entidades implements Serializable
{
    private static final long serialVersionUID = 1L;

    public Operaciones() {
        super();
    }
}
