/*
 * Java bean class for entity "procedencias" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;

import com.j256.ormlite.table.DatabaseTable;


/**
 * Java bean for entity "procedencias"
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "procedencias")
public class Origin extends EntityLong implements Serializable
{
    private static final long serialVersionUID = 1L;
    public Origin() {
        super();
    }
}
