/*
 * Java bean class for entity "parametros_goblales" 
 * Created on 2019-07-27 ( Date ISO 2019-07-27 - Time 22:46:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "parametros_goblales"
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParametrosGoblales implements Serializable
{
    private static final long serialVersionUID = 1L;

    private String    id           ; // Id or Primary Key

    private String     value        ;

    /**
     * Default constructor
     */
    public ParametrosGoblales() {
        super();
    }
    
    
    public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}

	//----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "value" field value
     * This field is mapped on the database column "value" ( type "VARCHAR", NotNull : false ) 
     * @param value
     */
    public void setValue( String value ) {
        this.value = value;
    }
    /**
     * Get the "value" field value
     * This field is mapped on the database column "value" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getValue() {
        return this.value;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(value);
        return sb.toString(); 
    } 

}
