/*
 * Created on 2019-10-06 ( Date ISO 2019-10-06 - Time 22:56:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.balanzasgj.app.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.io.Serializable;
import java.util.Date;

@DatabaseTable(tableName = "patentes")
public class Patent extends EntityString implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    @DatabaseField(canBeNull = true)
    private Double tara ;  // Double
    @DatabaseField(canBeNull = true, columnName = "dias")
    private int diasVenc ;  // Double
    @DatabaseField(canBeNull = false, columnName = "date_update")
    private Date update ;  // Date 

    /**
     * Default constructor
     */
    public Patent() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "tara" field value
     * This field is mapped on the database column "tara" ( type "DOUBLE", NotNull : true ) 
     * @param tara
     */
    public void setTara( Double tara ) {
        this.tara = tara;
    }
    /**
     * Get the "tara" field value
     * This field is mapped on the database column "tara" ( type "DOUBLE", NotNull : true ) 
     * @return the field value
     */
    public Double getTara() {
        return this.tara;
    }

    /**
     * Set the "update" field value
     * This field is mapped on the database column "update" ( type "DATETIME", NotNull : true ) 
     * @param update
     */
    public void setUpdate( Date update ) {
        this.update = update;
    }
    /**
     * Get the "update" field value
     * This field is mapped on the database column "update" ( type "DATETIME", NotNull : true ) 
     * @return the field value
     */
    public Date getUpdate() {
        return this.update;
    }

    public int getDiasVenc() {
		return diasVenc;
	}

	public void setDiasVenc(int diasVenc) {
		this.diasVenc = diasVenc;
	}		

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codigo);
        return sb.toString(); 
    } 



}
