/*
 * Created on 2019-10-06 ( Date ISO 2019-10-06 - Time 22:56:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.balanzasgj.app.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for entity "patentes" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class Patentes implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String codigo ; // String // Id or Primary Key
    private Double tara ;  // Double
    private int diasVenc ;  // Double 
    private Date update ;  // Date 

    /**
     * Default constructor
     */
    public Patentes() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "codigo" field value
     * This field is mapped on the database column "codigo" ( type "VARCHAR", NotNull : true ) 
     * @param codigo
     */
	public void setCodigo( String codigo ) {
        this.codigo = codigo ;
    }
    /**
     * Get the "codigo" field value
     * This field is mapped on the database column "codigo" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
	public String getCodigo() {
        return this.codigo;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "tara" field value
     * This field is mapped on the database column "tara" ( type "DOUBLE", NotNull : true ) 
     * @param tara
     */
    public void setTara( Double tara ) {
        this.tara = tara;
    }
    /**
     * Get the "tara" field value
     * This field is mapped on the database column "tara" ( type "DOUBLE", NotNull : true ) 
     * @return the field value
     */
    public Double getTara() {
        return this.tara;
    }

    /**
     * Set the "update" field value
     * This field is mapped on the database column "update" ( type "DATETIME", NotNull : true ) 
     * @param update
     */
    public void setUpdate( Date update ) {
        this.update = update;
    }
    /**
     * Get the "update" field value
     * This field is mapped on the database column "update" ( type "DATETIME", NotNull : true ) 
     * @return the field value
     */
    public Date getUpdate() {
        return this.update;
    }

    public int getDiasVenc() {
		return diasVenc;
	}

	public void setDiasVenc(int diasVenc) {
		this.diasVenc = diasVenc;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codigo);
        return sb.toString(); 
    } 



}
