/*
 * Java bean class for entity "productos" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "productos"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Productos extends Entidades implements Serializable
{
    private static final long serialVersionUID = 1L;
    private Integer    existencia   ;

    /**
     * Default constructor
     */
    public Productos() {
        super();
    }
    

    /**
     * Set the "existencia" field value
     * This field is mapped on the database column "existencia" ( type "INT", NotNull : false ) 
     * @param existencia
     */
    public void setExistencia( Integer existencia ) {
        this.existencia = existencia;
    }
    /**
     * Get the "existencia" field value
     * This field is mapped on the database column "existencia" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getExistencia() {
        return this.existencia;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();         
        sb.append(nombre);
        return sb.toString(); 
    } 

}
