/*
 * Java bean class for entity "productos" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


/**
 * Java bean for entity "productos"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Productos extends Entidades implements Serializable
{
    private static final long serialVersionUID = 1L;    
    

    /**
     * Default constructor
     */
    public Productos() {
        super();
    }

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();         
        sb.append(nombre);
        return sb.toString(); 
    } 

}
