/*
 * Java bean class for entity "productos" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;
import java.math.BigDecimal;

import com.balanzasgj.app.persistence.impl.jdbc.ProductDaoImpl;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;


/**
 * Java bean for entity "productos"
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "productos", daoClass = ProductDaoImpl.class)
public class Product extends Entity implements Serializable
{
    private static final long serialVersionUID = 1L;    

	@DatabaseField(canBeNull = true)
	protected String alias ;  // String 
	
	@DatabaseField(canBeNull = true)
	protected BigDecimal acumulado ; 

    /**
     * Default constructor
     */
    public Product() {
        super();
    }
    
    public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}
	
	public BigDecimal getAcumulado() {
		return acumulado;
	}

	public void setAcumulado(BigDecimal acumulado) {
		this.acumulado = acumulado;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer();         
        sb.append(nombre);
        return sb.toString(); 
    } 

}
