/*
 * Created on 2020-09-13 ( Date ISO 2020-09-13 - Time 21:03:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.balanzasgj.app.model;

import java.io.Serializable;


/**
 * Java bean for entity "reports" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class Reports implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Long id ; // Integer // Id or Primary Key

    private Long taraId ;  // Integer 
    private Integer count ;  // Integer 

    /**
     * Default constructor
     */
    public Reports() {
        super();
    }
    
   

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}

	

    public Long getTaraId() {
		return taraId;
	}



	public void setTaraId(Long taraId) {
		this.taraId = taraId;
	}



	/**
     * Set the "count" field value
     * This field is mapped on the database column "count" ( type "INT", NotNull : true ) 
     * @param count
     */
    public void setCount( Integer count ) {
        this.count = count;
    }
    /**
     * Get the "count" field value
     * This field is mapped on the database column "count" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getCount() {
        return this.count;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(taraId);
        sb.append("|");
        sb.append(count);
        return sb.toString(); 
    } 



}
