/*
 * Java bean class for entity "transportes" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.balanzasgj.app.model;

import java.io.Serializable;

import com.j256.ormlite.table.DatabaseTable;

/**
 * Java bean for entity "transportes"
 * 
 * @author Telosys Tools Generator
 *
 */
@DatabaseTable(tableName = "transportes")
public class Transport extends TransportEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	public Transport() {
		super();
	}
}
