/*
 * Created on 2019-12-28 ( Date ISO 2019-12-28 - Time 12:26:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.balanzasgj.app.persistence;

import com.balanzasgj.app.model.Ata;

/**
 * Persistence Interface for Ata.
 */
public interface AtaPersistence extends CommonPersistence<Ata>{

}