/*
 * Created on 2019-07-04 ( Date ISO 2019-07-04 - Time 19:20:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc.commons;

import java.sql.Connection;
import java.sql.SQLException;

import org.apache.log4j.Logger;

import com.j256.ormlite.dao.BaseDaoImpl;

/**
 * Generic abstract class for basic JDBC DAO
 * 
 * @author Telosys Tools
 *
 * @param <T>
 */
public abstract class GenericJdbcDAO<T, S> extends BaseDaoImpl<T, S>{	

	final static Logger logger = Logger.getLogger(GenericJdbcDAO.class);
	
	protected final static int INITIAL_POSITION = 1 ;
				
	public GenericJdbcDAO(Class<T> dataClass) throws SQLException  {			
		super(DataSourceProvider.getJdbcPooledConnectionSource(), dataClass);	
	}
		
	protected Connection getConnection() {
		try {
			return DataSourceProvider.getDataSource().getConnection();
		} catch (SQLException e) {}		
		return null;
	}
}

