/*
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 20:59:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;


import com.balanzasgj.app.model.AjustesDeStocks ;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * AjustesDeStocks persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("AjustesDeStocksPersistence")
public class AjustesDeStocksPersistenceJdbc extends GenericJdbcDAO<AjustesDeStocks> {

	private final static String SQL_SELECT_ALL = 
		"select codigo, nombre, existencia from ajustes_de_stocks"; 

	private final static String SQL_SELECT = 
		"select codigo, nombre, existencia from ajustes_de_stocks where codigo = ?";

	private final static String SQL_INSERT = 
		"insert into ajustes_de_stocks ( nombre, existencia ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update ajustes_de_stocks set nombre = ?, existencia = ? where codigo = ?";

	private final static String SQL_DELETE = 
		"delete from ajustes_de_stocks where codigo = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from ajustes_de_stocks";

	private final static String SQL_COUNT = 
		"select count(*) from ajustes_de_stocks where codigo = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public AjustesDeStocksPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(AjustesDeStocks record, long value) {
		record.setCodigo(value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, AjustesDeStocks ajustesDeStocks) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, ajustesDeStocks.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, AjustesDeStocks ajustesDeStocks) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert		
		setValue(ps, i++, ajustesDeStocks.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, ajustesDeStocks.getExistencia() ) ; // "existencia" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, AjustesDeStocks ajustesDeStocks) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, ajustesDeStocks.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, ajustesDeStocks.getExistencia() ) ; // "existencia" : java.lang.Integer
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, ajustesDeStocks.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private AjustesDeStocks newInstanceWithPrimaryKey( Long codigo ) {
		AjustesDeStocks ajustesDeStocks = new AjustesDeStocks();
		ajustesDeStocks.setCodigo( codigo );
		return ajustesDeStocks ;
	}

	//----------------------------------------------------------------------
	@Override
	protected AjustesDeStocks newInstance() {
		return new AjustesDeStocks() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected AjustesDeStocks populateBean(ResultSet rs, AjustesDeStocks ajustesDeStocks) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		ajustesDeStocks.setCodigo(rs.getLong("codigo")); // java.lang.Integer
		if ( rs.wasNull() ) { ajustesDeStocks.setCodigo(null); }; // not primitive number => keep null value if any
		ajustesDeStocks.setNombre(rs.getString("nombre")); // java.lang.String
		ajustesDeStocks.setExistencia(rs.getInt("existencia")); // java.lang.Integer
		if ( rs.wasNull() ) { ajustesDeStocks.setExistencia(null); }; // not primitive number => keep null value if any
		return ajustesDeStocks ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public AjustesDeStocks findById( Long codigo ) {
		AjustesDeStocks ajustesDeStocks = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(ajustesDeStocks) ) {
			return ajustesDeStocks ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public List<AjustesDeStocks> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param ajustesDeStocks
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( AjustesDeStocks ajustesDeStocks ) {
		return super.doSelect(ajustesDeStocks) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param ajustesDeStocks
	 */
	public long insert(AjustesDeStocks ajustesDeStocks) {
		Long key = super.doInsertAutoIncr(ajustesDeStocks);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public AjustesDeStocks create(AjustesDeStocks ajustesDeStocks) {
		insert(ajustesDeStocks);
		return ajustesDeStocks ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean update(AjustesDeStocks ajustesDeStocks) {
		int r = super.doUpdate(ajustesDeStocks);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public AjustesDeStocks save(AjustesDeStocks ajustesDeStocks) {
		if ( super.doExists(ajustesDeStocks) ) {
			super.doUpdate(ajustesDeStocks);
		}
		else {
			super.doInsert(ajustesDeStocks);
		}
		return ajustesDeStocks ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean deleteById( Long codigo ) {
		AjustesDeStocks ajustesDeStocks = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(ajustesDeStocks);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean delete( AjustesDeStocks ajustesDeStocks ) {
		int r = super.doDelete(ajustesDeStocks);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// @Override
	public boolean exists( Long codigo ) {
		AjustesDeStocks ajustesDeStocks = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(ajustesDeStocks);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param ajustesDeStocks
	 * @return
	 */
	// @Override
	public boolean exists( AjustesDeStocks ajustesDeStocks ) {
		return super.doExists(ajustesDeStocks);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
