/*
 * Created on 2019-12-28 ( Date ISO 2019-12-28 - Time 12:27:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.balanzasgj.app.model.Ata;
import com.balanzasgj.app.persistence.AtaPersistence;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * Ata persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("AtaPersistence")
public class AtaPersistenceJdbc extends GenericJdbcDAO<Ata> implements AtaPersistence {

	private final static String SQL_SELECT_ALL = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from ata"; 

	private final static String SQL_SELECT = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from ata where codigo = ?";

	private final static String SQL_INSERT = 
		"insert into ata ( nombre, CUIT, ultimo_movimiento, acumulado ) values ( ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update ata set nombre = ?, CUIT = ?, ultimo_movimiento = ?, acumulado = ? where codigo = ?";

	private final static String SQL_DELETE = 
		"delete from ata where codigo = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from ata";

	private final static String SQL_COUNT = 
		"select count(*) from ata where codigo = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public AtaPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(Ata ata, long value) {
		ata.setCodigo(value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Ata ata) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, ata.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Ata ata) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert		
		setValue(ps, i++, ata.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, ata.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, ata.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, ata.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Ata ata) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, ata.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, ata.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, ata.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, ata.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, ata.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private Ata newInstanceWithPrimaryKey( Long codigo ) {
		Ata ata = new Ata();
		ata.setCodigo( codigo );
		return ata ;
	}

	//----------------------------------------------------------------------
	@Override
	protected Ata newInstance() {
		return new Ata() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected Ata populateBean(ResultSet rs, Ata ata) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		ata.setCodigo(rs.getLong("codigo")); // java.lang.Integer
		if ( rs.wasNull() ) { ata.setCodigo(null); }; // not primitive number => keep null value if any
		ata.setNombre(rs.getString("nombre")); // java.lang.String
		ata.setCuit(rs.getString("CUIT")); // java.lang.String
		ata.setUltimoMovimiento(rs.getDate("ultimo_movimiento")); // java.util.Date
		ata.setAcumulado(rs.getBigDecimal("acumulado")); // java.math.BigDecimal
		if ( rs.wasNull() ) { ata.setAcumulado(null); }; // not primitive number => keep null value if any
		return ata ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public Ata findById( Long codigo ) {
		Ata ata = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(ata) ) {
			return ata ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public List<Ata> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param ata
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( Ata ata ) {
		return super.doSelect(ata) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param ata
	 */
	public long insert(Ata ata) {
		Long key = super.doInsertAutoIncr(ata);
		return key.longValue();
	}
 

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public Ata save(Ata ata) {
		if ( super.doExists(ata) ) {
			super.doUpdate(ata);
		}
		else {
			super.doInsert(ata);
		}
		return ata ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean deleteById( Long codigo ) {
		Ata ata = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(ata);
		return r > 0 ;
	}
    
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a  in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// @Override
	public boolean exists( Long codigo ) {
		Ata ata = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(ata);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param ata
	 * @return
	 */
	// @Override
	public boolean exists( Ata ata ) {
		return super.doExists(ata);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the s present in the database
	 * @return
	 */
	@Override
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
