/*
 * Created on 2019-11-19 ( Date ISO 2019-11-19 - Time 00:11:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.balanzasgj.app.model.ImportadoresExportadores;
import com.balanzasgj.app.persistence.ImportadoresExportadoresPersistence;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * ImportadoresExportadores persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("ImportadoresExportadoresPersistence")
public class ImportadoresExportadoresPersistenceJdbc extends GenericJdbcDAO<ImportadoresExportadores> implements ImportadoresExportadoresPersistence {

	private final static String SQL_SELECT_ALL = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from importadores_exportadores"; 

	private final static String SQL_SELECT = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from importadores_exportadores where codigo = ?";

	private final static String SQL_INSERT = 
		"insert into importadores_exportadores ( nombre, CUIT, ultimo_movimiento, acumulado ) values ( ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update importadores_exportadores set nombre = ?, CUIT = ?, ultimo_movimiento = ?, acumulado = ? where codigo = ?";

	private final static String SQL_DELETE = 
		"delete from importadores_exportadores where codigo = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from importadores_exportadores";

	private final static String SQL_COUNT = 
		"select count(*) from importadores_exportadores where codigo = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public ImportadoresExportadoresPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(ImportadoresExportadores record, long value) {
		record.setCodigo((long)value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, ImportadoresExportadores importadoresExportadores) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, importadoresExportadores.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, ImportadoresExportadores importadoresExportadores) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert		
		setValue(ps, i++, importadoresExportadores.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, importadoresExportadores.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, importadoresExportadores.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, importadoresExportadores.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, ImportadoresExportadores importadoresExportadores) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, importadoresExportadores.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, importadoresExportadores.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, importadoresExportadores.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, importadoresExportadores.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, importadoresExportadores.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private ImportadoresExportadores newInstanceWithPrimaryKey( long codigo ) {
		ImportadoresExportadores importadoresExportadores = new ImportadoresExportadores();
		importadoresExportadores.setCodigo( codigo );
		return importadoresExportadores ;
	}

	//----------------------------------------------------------------------
	@Override
	protected ImportadoresExportadores newInstance() {
		return new ImportadoresExportadores() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected ImportadoresExportadores populateBean(ResultSet rs, ImportadoresExportadores importadoresExportadores) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		importadoresExportadores.setCodigo(rs.getLong("codigo")); // java.lang.Integer
		if ( rs.wasNull() ) { importadoresExportadores.setCodigo(null); }; // not primitive number => keep null value if any
		importadoresExportadores.setNombre(rs.getString("nombre")); // java.lang.String
		importadoresExportadores.setCuit(rs.getString("CUIT")); // java.lang.String
		importadoresExportadores.setUltimoMovimiento(rs.getDate("ultimo_movimiento")); // java.util.Date
		importadoresExportadores.setAcumulado(rs.getBigDecimal("acumulado")); // java.math.BigDecimal
		if ( rs.wasNull() ) { importadoresExportadores.setAcumulado(null); }; // not primitive number => keep null value if any
		return importadoresExportadores ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public ImportadoresExportadores findById( Long codigo ) {
		ImportadoresExportadores importadoresExportadores = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(importadoresExportadores) ) {
			return importadoresExportadores ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public List<ImportadoresExportadores> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param importadoresExportadores
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( ImportadoresExportadores importadoresExportadores ) {
		return super.doSelect(importadoresExportadores) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param importadoresExportadores
	 */
	public long insert(ImportadoresExportadores importadoresExportadores) {
		Long key = super.doInsertAutoIncr(importadoresExportadores);
		return key.longValue();
	}

	public boolean update(ImportadoresExportadores importadoresExportadores) {
		int r = super.doUpdate(importadoresExportadores);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public ImportadoresExportadores save(ImportadoresExportadores importadoresExportadores) {
		if ( super.doExists(importadoresExportadores) ) {
			super.doUpdate(importadoresExportadores);
		}
		else {
			super.doInsert(importadoresExportadores);
		}
		return importadoresExportadores ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean deleteById( Long codigo ) {
		ImportadoresExportadores importadoresExportadores = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(importadoresExportadores);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// @Override
	public boolean exists( Integer codigo ) {
		ImportadoresExportadores importadoresExportadores = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(importadoresExportadores);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param importadoresExportadores
	 * @return
	 */
	// @Override
	public boolean exists( ImportadoresExportadores importadoresExportadores ) {
		return super.doExists(importadoresExportadores);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
