/*
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 20:59:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.balanzasgj.app.model.Operaciones;
import com.balanzasgj.app.persistence.OperacionesPersistence;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * Operaciones persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("OperacionesPersistence")
public class OperacionesPersistenceJdbc extends GenericJdbcDAO<Operaciones> implements OperacionesPersistence{

	private final static String SQL_SELECT_ALL = 
		"select codigo, nombre from operaciones"; 

	private final static String SQL_SELECT = 
		"select codigo, nombre from operaciones where codigo = ?";

	private final static String SQL_INSERT = 
		"insert into operaciones ( nombre ) values ( ? )";

	private final static String SQL_UPDATE = 
		"update operaciones set nombre = ? where codigo = ?";

	private final static String SQL_DELETE = 
		"delete from operaciones where codigo = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from operaciones";

	private final static String SQL_COUNT = 
		"select count(*) from operaciones where codigo = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public OperacionesPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(Operaciones record, long value) {
		record.setCodigo(value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Operaciones operaciones) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, operaciones.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Operaciones operaciones) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert		
		setValue(ps, i++, operaciones.getNombre() ) ; // "nombre" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Operaciones operaciones) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, operaciones.getNombre() ) ; // "nombre" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, operaciones.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private Operaciones newInstanceWithPrimaryKey( Long codigo ) {
		Operaciones operaciones = new Operaciones();
		operaciones.setCodigo( codigo );
		return operaciones ;
	}

	//----------------------------------------------------------------------
	@Override
	protected Operaciones newInstance() {
		return new Operaciones() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected Operaciones populateBean(ResultSet rs, Operaciones operaciones) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		operaciones.setCodigo(rs.getLong("codigo")); // java.lang.Integer
		if ( rs.wasNull() ) { operaciones.setCodigo(null); }; // not primitive number => keep null value if any
		operaciones.setNombre(rs.getString("nombre")); // java.lang.String
		return operaciones ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public Operaciones findById( Long codigo ) {
		Operaciones operaciones = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(operaciones) ) {
			return operaciones ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public List<Operaciones> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param operaciones
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( Operaciones operaciones ) {
		return super.doSelect(operaciones) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param operaciones
	 */
	public long insert(Operaciones operaciones) {
		Long key = super.doInsertAutoIncr(operaciones);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public Operaciones create(Operaciones operaciones) {
		insert(operaciones);
		return operaciones ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean update(Operaciones operaciones) {
		int r = super.doUpdate(operaciones);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public Operaciones save(Operaciones operaciones) {
		if ( super.doExists(operaciones) ) {
			super.doUpdate(operaciones);
		}
		else {
			super.doInsert(operaciones);
		}
		return operaciones ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean deleteById( Long codigo ) {
		Operaciones operaciones = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(operaciones);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean delete( Operaciones operaciones ) {
		int r = super.doDelete(operaciones);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// 
	public boolean exists( Long codigo ) {
		Operaciones operaciones = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(operaciones);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param operaciones
	 * @return
	 */
	// @Override
	public boolean exists( Operaciones operaciones ) {
		return super.doExists(operaciones);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */	
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
