/*
 * Created on 2019-07-27 ( Date ISO 2019-07-27 - Time 22:46:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.balanzasgj.app.basic.bean.ParametrosGoblales;
import com.balanzasgj.app.persistence.ParametrosGoblalesPersistence;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * ParametrosGoblales persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("ParametrosGoblalesPersistence")
public class ParametrosGoblalesPersistenceJdbc extends GenericJdbcDAO<ParametrosGoblales> implements ParametrosGoblalesPersistence {

	private final static String SQL_SELECT_ALL = 
		"select id, value from parametros_goblales"; 

	private final static String SQL_SELECT = 
		"select id, value from parametros_goblales where id = ?";

	private final static String SQL_INSERT = 
		"insert into parametros_goblales ( id, value ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update parametros_goblales set value = ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from parametros_goblales where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from parametros_goblales";

	private final static String SQL_COUNT = 
		"select count(*) from parametros_goblales where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public ParametrosGoblalesPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(ParametrosGoblales record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, ParametrosGoblales parametrosGoblales) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, parametrosGoblales.getId() ) ; // "id" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, ParametrosGoblales parametrosGoblales) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, parametrosGoblales.getId() ) ; // "id" : java.lang.Integer
		setValue(ps, i++, parametrosGoblales.getValue() ) ; // "value" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, ParametrosGoblales parametrosGoblales) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, parametrosGoblales.getValue() ) ; // "value" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, parametrosGoblales.getId() ) ; // "id" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param id;
	 * @return the new instance
	 */
	private ParametrosGoblales newInstanceWithPrimaryKey( String id ) {
		ParametrosGoblales parametrosGoblales = new ParametrosGoblales();
		parametrosGoblales.setId( id );
		return parametrosGoblales ;
	}

	//----------------------------------------------------------------------
	@Override
	protected ParametrosGoblales newInstance() {
		return new ParametrosGoblales() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected ParametrosGoblales populateBean(ResultSet rs, ParametrosGoblales parametrosGoblales) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		parametrosGoblales.setId(rs.getString("id")); // java.lang.Integer
		if ( rs.wasNull() ) { parametrosGoblales.setId(null); }; // not primitive number => keep null value if any
		parametrosGoblales.setValue(rs.getString("value")); // java.lang.String
		return parametrosGoblales ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public ParametrosGoblales findById( String id ) {
		ParametrosGoblales parametrosGoblales = newInstanceWithPrimaryKey( id ) ;
		if ( super.doSelect(parametrosGoblales) ) {
			return parametrosGoblales ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public List<ParametrosGoblales> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param parametrosGoblales
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( ParametrosGoblales parametrosGoblales ) {
		return super.doSelect(parametrosGoblales) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param parametrosGoblales
	 */
	public long insert(ParametrosGoblales parametrosGoblales) {
		super.doInsert(parametrosGoblales);
		return 0L ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */	
	public ParametrosGoblales create(ParametrosGoblales parametrosGoblales) {
		insert(parametrosGoblales);
		return parametrosGoblales ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */	
	public boolean update(ParametrosGoblales parametrosGoblales) {
		int r = super.doUpdate(parametrosGoblales);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public ParametrosGoblales save(ParametrosGoblales parametrosGoblales) {
		if ( super.doExists(parametrosGoblales) ) {
			super.doUpdate(parametrosGoblales);
		}
		else {
			super.doInsert(parametrosGoblales);
		}
		return parametrosGoblales ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean deleteById( String id ) {
		ParametrosGoblales parametrosGoblales = newInstanceWithPrimaryKey( id ) ;
		int r = super.doDelete(parametrosGoblales);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */	
	public boolean delete( ParametrosGoblales parametrosGoblales ) {
		int r = super.doDelete(parametrosGoblales);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id;
	 * @return
	 */
	// @Override
	public boolean exists( String id ) {
		ParametrosGoblales parametrosGoblales = newInstanceWithPrimaryKey( id ) ;
		return super.doExists(parametrosGoblales);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param parametrosGoblales
	 * @return
	 */
	// @Override
	public boolean exists( ParametrosGoblales parametrosGoblales ) {
		return super.doExists(parametrosGoblales);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
