/*
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 20:59:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.balanzasgj.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.balanzasgj.app.model.Transportes ;
import com.balanzasgj.app.persistence.TransportesPersistence;
import com.balanzasgj.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * Transportes persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("TransportesPersistence")
public class TransportesPersistenceJdbc extends GenericJdbcDAO<Transportes> implements TransportesPersistence {

	private final static String SQL_SELECT_ALL = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from transportes"; 

	private final static String SQL_SELECT = 
		"select codigo, nombre, CUIT, ultimo_movimiento, acumulado from transportes where codigo = ?";

	private final static String SQL_INSERT = 
		"insert into transportes ( nombre, CUIT, ultimo_movimiento, acumulado ) values ( ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update transportes set nombre = ?, CUIT = ?, ultimo_movimiento = ?, acumulado = ? where codigo = ?";

	private final static String SQL_DELETE = 
		"delete from transportes where codigo = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from transportes";

	private final static String SQL_COUNT = 
		"select count(*) from transportes where codigo = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public TransportesPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(Transportes record, long value) {
		record.setCodigo(value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Transportes transportes) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, transportes.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Transportes transportes) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert		
		setValue(ps, i++, transportes.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, transportes.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, transportes.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, transportes.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Transportes transportes) throws SQLException {
		setValue(ps, i++, transportes.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, transportes.getCuit() ) ; // "CUIT" : java.lang.String
		setValue(ps, i++, transportes.getUltimoMovimiento() ) ; // "ultimo_movimiento" : java.util.Date
		setValue(ps, i++, transportes.getAcumulado() ) ; // "acumulado" : java.math.BigDecimal
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, transportes.getCodigo() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private Transportes newInstanceWithPrimaryKey( Long codigo ) {
		Transportes transportes = new Transportes();
		transportes.setCodigo( codigo );
		return transportes ;
	}

	//----------------------------------------------------------------------
	@Override
	protected Transportes newInstance() {
		return new Transportes() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected Transportes populateBean(ResultSet rs, Transportes transportes) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		transportes.setCodigo(rs.getLong("codigo")); // java.lang.Integer
		if ( rs.wasNull() ) { transportes.setCodigo(null); }; // not primitive number => keep null value if any
		transportes.setNombre(rs.getString("nombre")); // java.lang.String
		transportes.setCuit(rs.getString("CUIT")); // java.lang.String
		transportes.setUltimoMovimiento(rs.getDate("ultimo_movimiento")); // java.util.Date
		transportes.setAcumulado(rs.getBigDecimal("acumulado")); // java.math.BigDecimal
		if ( rs.wasNull() ) { transportes.setAcumulado(null); }; // not primitive number => keep null value if any
		return transportes ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public Transportes findById( Long codigo ) {
		Transportes transportes = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(transportes) ) {
			return transportes ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public List<Transportes> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param transportes
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( Transportes transportes ) {
		return super.doSelect(transportes) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param transportes
	 */
	public long insert(Transportes transportes) {
		Long key = super.doInsertAutoIncr(transportes);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public Transportes create(Transportes transportes) {
		insert(transportes);
		return transportes ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean update(Transportes transportes) {
		int r = super.doUpdate(transportes);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public Transportes save(Transportes transportes) {
		if ( super.doExists(transportes) ) {
			super.doUpdate(transportes);
		}
		else {
			super.doInsert(transportes);
		}
		return transportes ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean deleteById( Long codigo ) {
		Transportes transportes = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(transportes);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public boolean delete( Transportes transportes ) {
		int r = super.doDelete(transportes);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// @Override
	public boolean exists( Long codigo ) {
		Transportes transportes = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(transportes);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param transportes
	 * @return
	 */
	// @Override
	public boolean exists( Transportes transportes ) {
		return super.doExists(transportes);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
